### ISSUE TITLE
post_select broken?

### ISSUE THREAD

**Issue by jdmoliner** [wp-shortcake/shortcake#545]
Hi,

I can not run post_select with WP 4.3.1 and  shortcake 0.6.1. 

It should work? or am I doing something wrong? I get always 'No results were found'

**Comment by danielbachhuber** [comment]
Can you share how you've defined your shortcode UI, and the query you're trying to make?

**Comment by jdmoliner** [comment]
I used the same example as in dev.php:

<pre>
 function shortcode_ui_dev_advanced_example() { 
    shortcode_ui_register_for_shortcode( 'shortcake_dev',
        array(          
            'label' => esc_html__( 'Botón', 'shortcode-ui' ),          
            'listItemImage' => 'dashicons-editor-quote',            
            'attrs' => array(   
                array(
                    'label' => esc_html__( 'Select Page', 'shortcode-ui' ),
                    'attr' => 'page',
                    'type' => 'post_select',
                    'query' => array( 'post_type' => 'page' ),
                    'multiple' => true,
                )
            )
        )
    );
 }
 add_action( 'register_shortcode_ui', 'shortcode_ui_dev_advanced_example' );
</pre>

**Comment by danielbachhuber** [comment]
I've confirmed the bug :( We'll get this fixed in v0.6.2.

For now, you can address the bug locally by registering your UI on `init`, and adding a `function_exists()` check for `shortcode_ui_register_for_shortcode`

**Comment by danielbachhuber** [comment]
@jdmoliner Just released v0.6.2 if you care to upgrade instead.

**Comment by widoz** [comment]
Installed the 0.6.2 but the issue remains.

This is what I seen on console.

> Uncaught Error: No select2/compat/initSelection

May be a different issue?

**Comment by widoz** [comment]
Sorry, found another thread with the same issue of mine.
